JsonCpp - JSON data format manipulation library
JsonCpp project page JsonCpp home page
Json::ValueIteratorBase Class Reference
base class for Value iterators.
#include <json/value.h>
Inherited by Json::ValueConstIterator, and Json::ValueIterator.
Public Types
typedef
std::bidirectional_iterator_tag iterator_category
typedef unsigned int size_t
typedef int difference_type
typedef ValueIteratorBase SelfType
Public Member Functions
ValueIteratorBase ()
ValueIteratorBase (const ValueInternalArray::IteratorState &state)
ValueIteratorBase (const ValueInternalMap::IteratorState &state)
bool operator== (const SelfType &other) const
bool operator!= (const SelfType &other) const
difference_type operator- (const SelfType &other) const
Value key () const
Return either the index or the member name of the referenced value as a Value.
UInt index () const
Return the index of the referenced Value. -1 if it is not an arrayValue.
const char * memberName () const
Return the member name of the referenced Value.
Protected Member Functions
Value & deref () const
void increment ()
void decrement ()
difference_type computeDistance (const SelfType &other) const
bool isEqual (const SelfType &other) const
void copy (const SelfType &other)
Detailed Description
base class for Value iterators.
Definition at line 928 of file value.h.
Member Typedef Documentation
typedef int Json::ValueIteratorBase::difference_type
Definition at line 932 of file value.h.
typedef std::bidirectional_iterator_tag Json::ValueIteratorBase::iterator_category
Definition at line 930 of file value.h.
typedef ValueIteratorBase Json::ValueIteratorBase::SelfType
Definition at line 933 of file value.h.
typedef unsigned int Json::ValueIteratorBase::size_t
Definition at line 931 of file value.h.
Constructor & Destructor Documentation
Json::ValueIteratorBase::ValueIteratorBase ()
Definition at line 18 of file json_valueiterator.inl.
Json::ValueIteratorBase::ValueIteratorBase (const ValueInternalArray::IteratorState & state)
Definition at line 33 of file json_valueiterator.inl.
Json::ValueIteratorBase::ValueIteratorBase (const ValueInternalMap::IteratorState & state)
Definition at line 39 of file json_valueiterator.inl.
Member Function Documentation
ValueIteratorBase::difference_type Json::ValueIteratorBase::computeDistance (const SelfType & other) const protected
Definition at line 77 of file json_valueiterator.inl.
References array_, and map_.
void Json::ValueIteratorBase::copy (const SelfType & other) protected
Definition at line 124 of file json_valueiterator.inl.
References array_, and map_.
Referenced by Json::ValueConstIterator::operator=(), and Json::ValueIterator::operator=().
void Json::ValueIteratorBase::decrement () protected
Definition at line 66 of file json_valueiterator.inl.
Value & Json::ValueIteratorBase::deref () const protected
Definition at line 46 of file json_valueiterator.inl.
void Json::ValueIteratorBase::increment () protected
Definition at line 56 of file json_valueiterator.inl.
UInt Json::ValueIteratorBase::index () const
Return the index of the referenced Value. -1 if it is not an arrayValue.
Definition at line 155 of file json_valueiterator.inl.
bool Json::ValueIteratorBase::isEqual (const SelfType & other) const protected
Definition at line 111 of file json_valueiterator.inl.
References array_, and map_.
Value Json::ValueIteratorBase::key () const
Return either the index or the member name of the referenced value as a Value.
Definition at line 135 of file json_valueiterator.inl.
References memberName().
const char * Json::ValueIteratorBase::memberName () const
Return the member name of the referenced Value.
"" if it is not an objectValue.
Definition at line 168 of file json_valueiterator.inl.
Referenced by key().
bool Json::ValueIteratorBase::operator!= (const SelfType & other) const inline
Definition at line 945 of file value.h.
difference_type Json::ValueIteratorBase::operator- (const SelfType & other) const inline
Definition at line 947 of file value.h.
bool Json::ValueIteratorBase::operator== (const SelfType & other) const inline
Definition at line 943 of file value.h.
Member Data Documentation
ValueInternalArray::IteratorState Json::ValueIteratorBase::array_
Definition at line 982 of file value.h.
Referenced by computeDistance(), copy(), and isEqual().
ValueInternalMap::IteratorState Json::ValueIteratorBase::map_
Definition at line 983 of file value.h.
Referenced by computeDistance(), copy(), and isEqual().
The documentation for this class was generated from the following files:
include/json/value.h
src/lib_json/json_valueiterator.inl