JsonCpp - JSON data format manipulation library
JsonCpp project page JsonCpp home page
Json::StreamWriter::Builder Class Reference
Because this Builder is non-virtual, we can safely add methods without a major version bump.
#include <json/writer.h>
Public Member Functions
Builder ()
~Builder ()
Builder & withCommentStyle (CommentStyle cs)
Builder & withIndentation (std::string indentation)
default: All
Builder & withDropNullPlaceholders (bool v)
Drop the "null" string from the writer's output for nullValues.
Builder & withOmitEndingLineFeed (bool v)
Do not add
at end of document.
Builder & withEnableYAMLCompatibility (bool v)
Add a space after ':'.
StreamWriter * newStreamWriter (std::ostream *sout) const
Do not take ownership of sout, but maintain a reference.
Detailed Description
Because this Builder is non-virtual, we can safely add methods without a major version bump.
See also
http://stackoverflow.com/questions/14875052/pure-virtual-functions-and-binary-compatibility
Definition at line 61 of file writer.h.
Constructor & Destructor Documentation
Json::StreamWriter::Builder::Builder ()
Definition at line 1048 of file json_writer.cpp.
Json::StreamWriter::Builder::~Builder ()
Definition at line 1052 of file json_writer.cpp.
Member Function Documentation
StreamWriter * Json::StreamWriter::Builder::newStreamWriter (std::ostream * sout) const
Do not take ownership of sout, but maintain a reference.
Definition at line 1086 of file json_writer.cpp.
Referenced by Json::operator<<(), and Json::writeString().
StreamWriter::Builder & Json::StreamWriter::Builder::withCommentStyle (CommentStyle cs)
Definition at line 1061 of file json_writer.cpp.
Referenced by Json::operator<<().
StreamWriter::Builder & Json::StreamWriter::Builder::withDropNullPlaceholders (bool v)
Drop the "null" string from the writer's output for nullValues.
Strictly speaking, this is not valid JSON. But when the output is being fed to a browser's Javascript, it makes for smaller output and the browser can handle the output just fine.
Definition at line 1071 of file json_writer.cpp.
StreamWriter::Builder & Json::StreamWriter::Builder::withEnableYAMLCompatibility (bool v)
Add a space after ':'.
If indentation is non-empty, we surround colon with whitespace, e.g. " : " This will add back the trailing space when there is no indentation. This seems dubious when the entire document is on a single line, but we leave this here to repduce the behavior of the old FastWriter.
Definition at line 1081 of file json_writer.cpp.
StreamWriter::Builder & Json::StreamWriter::Builder::withIndentation (std::string indentation)
default: All
Write in human-friendly style.
If "", then skip all indentation, newlines, and comments, which implies CommentStyle::None. Default: "\t"
Definition at line 1066 of file json_writer.cpp.
Referenced by Json::operator<<().
StreamWriter::Builder & Json::StreamWriter::Builder::withOmitEndingLineFeed (bool v)
Do not add
at end of document.
Normally, we add an extra newline, just because.
Definition at line 1076 of file json_writer.cpp.
The documentation for this class was generated from the following files:
include/json/writer.h
src/lib_json/json_writer.cpp