JsonCpp - JSON data format manipulation library
JsonCpp project page JsonCpp home page
Json Namespace Reference
JSON (JavaScript Object Notation).
Classes
class FastWriter
Outputs a Value in JSON format without formatting (not human friendly).
class Features
Configuration passed to reader and writer.
class OldCompressingStreamWriterBuilder
Build a StreamWriter implementation.
class Path
Experimental and untested: represents a "path" to access a node.
class PathArgument
Experimental and untested: represents an element of the "path" to access a node.
class Reader
Unserialize a JSON document into a Value.
class StaticString
Lightweight wrapper to tag static string.
class StreamWriter
Usage:
class StreamWriterBuilder
Build a StreamWriter implementation.
class StyledStreamWriter
Writes a Value in JSON format in a human friendly way, to a stream rather than to a string.
class StyledWriter
Writes a Value in JSON format in a human friendly way.
class Value
Represents a JSON value.
class ValueArrayAllocator
Experimental: do not use.
class ValueConstIterator
const iterator for object and array value.
class ValueInternalArray
A simplified deque implementation used internally by Value.
class ValueInternalLink
ValueInternalMap hash-map bucket chain link (for internal use only).
class ValueInternalMap
A linked page based hash-table implementation used internally by Value.
class ValueIterator
Iterator for object and array value.
class ValueIteratorBase
base class for Value iterators.
class ValueMapAllocator
Allocator to customize Value internal map.
class Writer
Abstract class for writers.
Typedefs
typedef int Int
typedef unsigned int UInt
typedef __int64 Int64
typedef unsigned __int64 UInt64
typedef Int64 LargestInt
typedef UInt64 LargestUInt
typedef unsigned int ArrayIndex
typedef char UIntToStringBuffer [uintToStringBufferSize]
Enumerations
enum ValueType {
nullValue = 0, intValue, uintValue, realValue,
stringValue, booleanValue, arrayValue, objectValue
}
Type of the value held by a Value object.
enum CommentPlacement { commentBefore = 0, commentAfterOnSameLine, commentAfter, numberOfCommentPlacement }
enum { uintToStringBufferSize = 3 * sizeof(LargestUInt) + 1 }
Functions
std::istream & operator>> (std::istream &, Value &)
Read from 'sin' into 'root'.
std::string writeString (Value const &root, StreamWriter::Factory const &factory)
Write into stringstream, then return string, for convenience.
std::string valueToString (Int value)
std::string valueToString (UInt value)
std::string valueToString (LargestInt value)
std::string valueToString (LargestUInt value)
std::string valueToString (double value)
std::string valueToString (bool value)
std::string valueToQuotedString (const char *value)
std::ostream & operator<< (std::ostream &, const Value &root)
Output using the StyledStreamWriter.
static ValueArrayAllocator *& arrayAllocator ()
static ValueMapAllocator *& mapAllocator ()
static bool containsNewLine (Reader::Location begin, Reader::Location end)
static std::string normalizeEOL (Reader::Location begin, Reader::Location end)
static std::string codePointToUTF8 (unsigned int cp)
Converts a unicode code-point to UTF-8.
static bool isControlCharacter (char ch)
Returns true if ch is a control character (in range [0,32[).
static void uintToString (LargestUInt value, char *&current)
Converts an unsigned integer to string.
static void fixNumericLocale (char *begin, char *end)
Change ',' to '.
template<typename T , typename U >
static bool InRange (double d, T min, U max)
static char * duplicateStringValue (const char *value, unsigned int length=unknown)
Duplicates the specified string value.
static void releaseStringValue (char *value)
Free the string duplicated by duplicateStringValue().
static bool IsIntegral (double d)
static bool containsControlCharacter (const char *str)
Variables
static struct
Json::DummyArrayAllocatorInitializer dummyArrayAllocatorInitializer
static struct
Json::DummyMapAllocatorInitializer dummyMapAllocatorInitializer
static const unsigned char kNull [sizeof(Value)] = { 0 }
const unsigned char & kNullRef = kNull[0]
static const double maxUInt64AsDouble = 18446744073709551615.0
static const unsigned int unknown = (unsigned)-1
Unknown size marker.
Detailed Description
JSON (JavaScript Object Notation).
Typedef Documentation
typedef unsigned int Json::ArrayIndex
Definition at line 23 of file forwards.h.
typedef int Json::Int
Definition at line 91 of file config.h.
typedef __int64 Json::Int64
Definition at line 100 of file config.h.
typedef Int64 Json::LargestInt
Definition at line 106 of file config.h.
typedef UInt64 Json::LargestUInt
Definition at line 107 of file config.h.
typedef unsigned int Json::UInt
Definition at line 92 of file config.h.
typedef unsigned __int64 Json::UInt64
Definition at line 101 of file config.h.
typedef char Json::UIntToStringBuffer[uintToStringBufferSize]
Definition at line 56 of file json_tool.h.
Enumeration Type Documentation
anonymous enum
Enumerator
uintToStringBufferSize
Constant that specify the size of the buffer that must be passed to uintToString.
Definition at line 49 of file json_tool.h.
enum Json::CommentPlacement
Enumerator
commentBefore
a comment placed on the line before a value
commentAfterOnSameLine
a comment just after a value on the same line
commentAfter
a comment on the line after a value (only make sense for
numberOfCommentPlacement
root value)
Definition at line 48 of file value.h.
enum Json::ValueType
Type of the value held by a Value object.
Enumerator
nullValue
'null' value
intValue
signed integer value
uintValue
unsigned integer value
realValue
double value
stringValue
UTF-8 string value.
booleanValue
bool value
arrayValue
array value (ordered list)
objectValue
object value (collection of name/value pairs).
Definition at line 37 of file value.h.
Function Documentation
static ValueArrayAllocator*& Json::arrayAllocator () static
Definition at line 123 of file json_internalarray.inl.
Referenced by Json::ValueInternalArray::resize(), Json::Value::Value(), Json::ValueInternalArray::ValueInternalArray(), Json::Value::~Value(), and Json::ValueInternalArray::~ValueInternalArray().
static std::string Json::codePointToUTF8 (unsigned int cp) inline static
Converts a unicode code-point to UTF-8.
Definition at line 18 of file json_tool.h.
static bool Json::containsControlCharacter (const char * str) static
Definition at line 37 of file json_writer.cpp.
References isControlCharacter().
Referenced by valueToQuotedString().
static bool Json::containsNewLine (Reader::Location begin, Reader::Location end) static
Definition at line 50 of file json_reader.cpp.
static char* Json::duplicateStringValue (const char * value, unsigned int length = unknown) inline static
Duplicates the specified string value.
Parameters
value Pointer to the string to duplicate. Must be zero-terminated if length is "unknown".
length Length of the value. if equals to unknown, then it will be computed using strlen(value).
Returns
Pointer on the duplicate instance of string.
Definition at line 86 of file json_value.cpp.
References JSON_ASSERT_MESSAGE, Json::Value::maxInt, and unknown.
Referenced by Json::Value::Value().
static void Json::fixNumericLocale (char * begin, char * end) inline static
Change ',' to '.
' everywhere in buffer.
We had a sophisticated way, but it did not work in WinCE.
See also
https://github.com/open-source-parsers/jsoncpp/pull/9
Definition at line 76 of file json_tool.h.
Referenced by valueToString().
template<typename T , typename U > static bool Json::InRange (double d, T min, U max) inline static
Definition at line 61 of file json_value.cpp.
Referenced by Json::Value::asInt(), Json::Value::asInt64(), Json::Value::asUInt(), Json::Value::asUInt64(), and Json::Value::isConvertibleTo().
static bool Json::isControlCharacter (char ch) inline static
Returns true if ch is a control character (in range [0,32[).
Definition at line 47 of file json_tool.h.
Referenced by containsControlCharacter(), and valueToQuotedString().
static bool Json::IsIntegral (double d) static
Definition at line 1134 of file json_value.cpp.
Referenced by Json::Value::isInt(), Json::Value::isInt64(), Json::Value::isUInt(), and Json::Value::isUInt64().
static ValueMapAllocator*& Json::mapAllocator () static
Definition at line 105 of file json_internalmap.inl.
Referenced by Json::ValueInternalMap::doActualRemove(), Json::ValueInternalMap::reserve(), Json::ValueInternalMap::unsafeAdd(), Json::Value::Value(), Json::Value::~Value(), and Json::ValueInternalMap::~ValueInternalMap().
static std::string Json::normalizeEOL (Reader::Location begin, Reader::Location end) static
Definition at line 332 of file json_reader.cpp.
std::ostream & Json::operator<< (std::ostream & sout, const Value & root)
Output using the StyledStreamWriter.
See also
Json::operator>>()
Definition at line 1021 of file json_writer.cpp.
References Json::StreamWriterBuilder::newStreamWriter().
std::istream & Json::operator>> (std::istream & sin, Value & root)
Read from 'sin' into 'root'.
Always keep comments from the input JSON.
This can be used to read a file into a particular sub-object. For example:
Json::Value root;
cin >> root["dir"]["file"];
cout << root;
Result:
{
"dir": {
    "file": {
    // The input stream JSON would be nested here.
    }
}
}
Exceptions
std::exception on parse error.
See also
Json::operator<<()
Definition at line 885 of file json_reader.cpp.
References Json::Reader::getFormattedErrorMessages(), JSON_FAIL_MESSAGE, and Json::Reader::parse().
static void Json::releaseStringValue (char * value) inline static
Free the string duplicated by duplicateStringValue().
Definition at line 107 of file json_value.cpp.
Referenced by Json::Value::~Value().
static void Json::uintToString (LargestUInt value, char *& current) inline static
Converts an unsigned integer to string.
Parameters
value Unsigned interger to convert to string
current Input/Output string buffer. Must have at least uintToStringBufferSize chars free.
Definition at line 63 of file json_tool.h.
Referenced by valueToString().
std::string Json::valueToQuotedString (const char * value)
Definition at line 117 of file json_writer.cpp.
References containsControlCharacter(), and isControlCharacter().
std::string Json::valueToString (Int value)
Definition at line 68 of file json_writer.cpp.
Referenced by Json::Value::asString(), and valueToString().
std::string Json::valueToString (UInt value)
Definition at line 72 of file json_writer.cpp.
References valueToString().
std::string Json::valueToString (LargestInt value)
Definition at line 45 of file json_writer.cpp.
References uintToString().
std::string Json::valueToString (LargestUInt value)
Definition at line 58 of file json_writer.cpp.
References uintToString().
std::string Json::valueToString (double value)
Definition at line 78 of file json_writer.cpp.
References fixNumericLocale(), isfinite, and snprintf.
std::string Json::valueToString (bool value)
Definition at line 115 of file json_writer.cpp.
std::string Json::writeString (Value const & root, StreamWriter::Factory const & factory)
Write into stringstream, then return string, for convenience.
Definition at line 1014 of file json_writer.cpp.
References Json::StreamWriter::Factory::newStreamWriter().
Variable Documentation
struct Json::DummyArrayAllocatorInitializer Json::dummyArrayAllocatorInitializer static
struct Json::DummyMapAllocatorInitializer Json::dummyMapAllocatorInitializer static
const unsigned char Json::kNull[sizeof(Value)] = { 0 } static
Definition at line 36 of file json_value.cpp.
const unsigned char& Json::kNullRef = kNull[0]
Definition at line 37 of file json_value.cpp.
const double Json::maxUInt64AsDouble = 18446744073709551615.0 static
Definition at line 50 of file json_value.cpp.
Referenced by Json::Value::isUInt64().
const unsigned int Json::unknown = (unsigned)-1 static
Unknown size marker.
Definition at line 57 of file json_value.cpp.
Referenced by duplicateStringValue().